GET http://localhost:3000/urls

###

POST http://localhost:5000/api/shorten 
Content-Type: application/json

{
"longURL": "https://www.google.com/"
}

###

DELETE http://localhost:5000/todo/delete/60e585eb6177f95ff0574326

###

GET http://localhost:5000/todo/complete/60e585d86177f95ff0574323

###

PUT http://localhost:5000/todo/update/60e585d86177f95ff0574323 
Content-Type: application/json

{
"text": "Go Shopping for Milk"
}

